site_name: MenuMh

theme:
  name: material

nav_style : dark

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Utilisation: utilisation.md
  - Configuration: configuration.md
  - FAQ: faq.md
  - Staff: Staff.md
