site_name: MenuMh

theme:
  name: material

nav_style : dark

nav:
  - Accueil: index.md
  - Installation: installation.md
  - Utilisation: utilisation.md
  - Configuration: configuration.md
  - FAQ: faq.md
  - Accueil Staff: Staff.md
  - Action Joueur : Action_Joueuer.md
  - Action Véhicule : Véhicule.md
  - Action Serveur : Serveur.md
